### ISSUE TITLE
add PyLODE implementation for ontologies

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/NS#1]
github action via makefile using pylode

- converts into /onto1.2.3.html
- commit and push to separate branch 'pylode-public'
- link that branch to github.io pages - add subfolder /ns

**Comment by marc-portier** [comment]
the project to deal with this is started at --> https://github.com/vliz-be-opsci/pylode-to-pages

**Comment by marc-portier** [comment]
pylode action is ready (although still in draft release) 
your evaluation of the outcome is appreciated (will release soon unless important remarks are raised)

closing this already - reopen or create new issues at https://github.com/vliz-be-opsci/pylode-to-pages
