### ISSUE TITLE
cname proper domain

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/NS#3]
e.g. open-voc.vliz.be

(consider HTTPS)

and then allocate the actual chosen host

Think of a name that can be used not only for ontologies but also to store static websites etc

**Comment by cedricdcc** [comment]
chosen for opsci.vliz.be

**Comment by RoryMMMM** [comment]
Need to double check with VLiz comms dept FIRST

**Comment by RoryMMMM** [comment]
Also remember the other CNAME we need:
issue #1

**Comment by marc-portier** [comment]
talked to communication dept -- useful tip was to avoid acronyms because they add up to unnecessary threshold
their advise is to go for one of: 
- open-vocabularies.vliz.be, 
- openscience-vocabularies.vliz.be
- vocabularies.vliz.be
otherwise no objections to **vliz.be hostnames in principle

**Comment by marc-portier** [comment]
> Also remember the other CNAME we need: issue #1

@RoryMMMM I assume you wanted to refer to this: https://github.com/vliz-be-opsci/vliz-be-opsci.github.io/issues/1 (other project)

**Comment by RoryMMMM** [comment]
We probably need to collect all the domain names we have, and use, in a list so we can keep track of them and any issues like DNS payments, letsencrypt renewal etc. If we expand this then it's likely that some might fall through the cracks.

Currently there are a few domain names that we have/need control over:
- https://data.ocean-sampling-day.org/  : points to the [project space repo ](https://github.com/ocean-sampling-day/ocean-sampling-day.github.io)
-  https://data.ocean-sampling-day.org/  `<project name>` : points to OSD child repo's
- `<something>`.vliz.be : should point to [opsci github parent](https://github.com/vliz-be-opsci/vliz-be-opsci.github.io)
- `<something>`.vliz.be/`<project name>` : should point to child repo's in the vliz-be-opsci space
- open-voc.vliz.be (or the updated name) : points to this specific vocab project
- OpenAIS: Just mentioning it.
- others?

**Comment by marc-portier** [comment]
now #1 got done - we can progress on this

**Comment by marc-portier** [comment]
also --> don't forget to add a proper `baseuri` (reflecting the chosen cname) into the `.github/workflow/pylode-to-pages.yml` at https://github.com/vliz-be-opsci/NS/blob/main/.github/workflows/pylode-to-pages.yml#L21

**Comment by marc-portier** [comment]
https://open-vocabularies.vliz.be/ is up and running
even redirects to when going to https://open-science.vliz.be/NS
