### ISSUE TITLE
consider introduction of terms for BON-columns

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/NS#6]
making sure we document recurring columns in the dmbon work

idea is to keep these terms distinct from the dmbonassistant as 
- these should cover describing the data
- the other drive behaviour of the code dmbon-assistant

**Comment by laurianvm** [comment]
Given the current structure of the emo-bon ontologies (available at: https://data.emobon.embrc.eu/ns/), there is no risk of potential confusion with the dmbon-assistant ontology.
